# Generated by Django 4.0.2 on 2022-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinats',
            name='pointer',
            field=models.TextField(max_length=255),
        ),
    ]
